name: task_app

services:
  server:
    container_name: server
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - ../configs/.env
    networks:
      - app_net
    depends_on:
      - subscriptions_db

  subscriptions_db:
    container_name: subscriptions_db
    image: postgres:latest
    env_file:
      - ../configs/.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ../db_data/subscriptions:/var/lib/postgresql
    networks:
      - app_net

networks:
  app_net:
    driver: bridge