name: task_app

services:
  server:
    container_name: server
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../configs/.env
    networks:
      - app_net
    depends_on:
      - subscriptions_db

  subscriptions_db:
    container_name: subscriptions_db
    image: postgres:latest
    env_file:
      - ../configs/.env
    ports:
      - "5432:5432"
    volumes:
      - ../db_data/subscriptions:/var/lib/postgresql/data
    networks:
      - app_net

networks:
  app_net:
    driver: bridge